[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'qpkorr/vim-renamer'

[[plugins]]
repo = 'hrp/EnhancedCommentify'

[[plugins]]
repo = 'vim-scripts/zoom.vim'

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'rhysd/nyaovim-markdown-preview'

[[plugins]]
repo = 'rhysd/nyaovim-popup-tooltip'

[[plugins]]
repo = 'rhysd/nyaovim-mini-browser'
